# Generated by Django 3.1.7 on 2021-03-19 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_auto_20210319_2200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['creation_date']},
        ),
    ]
